import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import GridContainer from "@/components/shared/grid-container/GridContainer.component";
import Sidebar from "@/components/shared/navigation/sidebar/Sidebar.component";
import Header from "@/components/shared/navigation/header/Header.component";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`background ${montserrat.className} antialiased`}
        style={montserrat.style}
      >
        <GridContainer cols={12}>
          <Sidebar />
          <main className="w-full min-h-screen h-full lg:col-span-10 col-span-full overflow-auto">
            <Header />
            {children}
          </main>
        </GridContainer>
      </body>
    </html>
  );
}
